伊利商城/apps/cart/urls.py
from django.contrib import admin
# from django.urls import path
from django.conf.urls import url,include
from .views import CartAddView,CartInfoView,CartUpdateView,CartDelView

urlpatterns = [
    url('add/',CartAddView.as_view(),name='add'),
    url('update/',CartUpdateView.as_view(),name='update'),
    url('del/',CartDelView.as_view(),name='del'),
    url('^',CartInfoView.as_view(),name='list'),
]

伊利商城/apps/goods/urls.py
from django.contrib import admin
# from django.urls import path
from django.conf.urls import url,include

from .views import IndexView,goods_listView,DetailView

urlpatterns = [
    url('index/$', IndexView.as_view(), name='index'),
    url('list/(?P<type_id>\d+)/(?P<pages>\d+)/$', goods_listView.as_view(), name='list'),
    url(r'detail/(?P<good_id>\d+)/$', DetailView.as_view(), name='detail'),

]

伊利商城/apps/order/urls.py
from django.contrib import admin
# from django.urls import path
from django.conf.urls import url,include
from .views import OrderPlaceView,OrderCommitView,OrderPayView,CommentView

urlpatterns = [
    url(r'place$',OrderPlaceView.as_view(),name='place'),      #提交页面订单显示
    url(r'commit$',OrderCommitView.as_view(),name='commit'),
    url(r'pay$',OrderPayView.as_view(),name='pay'),
    url(r'comment/(?P<order_id>.+)$',CommentView.as_view(),name='comment')

]

伊利商城/apps/user/urls.py
from django.contrib import admin
# from django.urls import path
from django.conf.urls import url,include
from .views import RegisterView,LoginView,ActiveView,UserInfoView,UserOrderView,UserSiteView

urlpatterns = [
    url('active/(?P<token>.*)/$',ActiveView.as_view(),name='active'),
    url('info/$', UserInfoView.as_view(), name='info'),
    url('order/(?P<page>\d+)$', UserOrderView.as_view(), name='order'),
    url('site/$', UserSiteView.as_view(), name='site'),
]

伊利商城/yili/urls.py
from django.contrib import admin
# from django.urls import path
from django.conf.urls import url,include
from user.views import RegisterView,LoginView,LogoutView
urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'tinymce/',include('tinymce.urls')),
    url(r'^search/', include('haystack.urls')), #全文检索框架
    # 注册
    url('^register/$', RegisterView.as_view(), name='register'),
    url('^login/$', LoginView.as_view(), name='login'),
    url('^logout/$', LogoutView.as_view(), name='logout'),

    url(r'^user/',include(('user.urls','user'),namespace='user')),
    url(r'^cart/',include(('cart.urls','cart'),namespace='cart')),
    url(r'^order/',include(('order.urls','order'),namespace='order')),
    url(r'^',include(('goods.urls','goods'),namespace='goods')),
]

伊利商城/apps/cart/models.py
from django.db import models

# Create your models here.

伊利商城/apps/cart/views.py
# 添加商品购物车：
# (1)请求方式，采用ajax
#       如果涉及到数据的修改（新增，更新，删除）,采用post
#       如果只涉及到数据的获取，采用get
# (2)传递的参数：商品id  商品数量
#     Get传参：/cart/add?sku_id=1&count=3
# 	  Post传参：{‘shu_id’:1,’count’:3}
# 	  url传参：url配置时捕获参数

#ajax发起的请求都在后台，在浏览器中看不到效果
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse

from goods.models import GoodsSKU
from django_redis import get_redis_connection
from utils.mixin import LoginRequiredMixin

#/cart/add
#购物车添加类使用了ajax post请求，这里不能使用LoginRequiredMixin类判断用户是否登录
#使用if not user.is_authenticated判断用户登录
class CartAddView(View):
    """购物车记录添加"""
    def post(self,request):
        """购物车记录添加"""
        print("1111")
        user = request.user
        if not user.is_authenticated:
            #用户未登录
            return JsonResponse({'res':0,'errmsg':'用户未登录'})
        #接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        #数据校验
        if not all([sku_id,count]):
            return JsonResponse({'res':1,'errmsg':'数据不完整'})
        # 校验添加的商品数量
        try:
            count = int(count)
        except Exception as e:
            #数目出错
            return JsonResponse({'res':2,'errmsg':'商品数目出错'})
        #校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            #商品不存在
            return  JsonResponse({'res':3,'errmsg':'商品不存在'})

        # 业务处理：添加购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id
        #先尝试获取sku_id的值 ->  hget cart_key 属性
        #如果sku_id在hash不存在，hget返回None
        cart_count = conn.hget(cart_key,sku_id)
        if cart_count:
            #累加购物车中商品的数目
            count += int(cart_count)
        #校验商品的库存
        if count > sku.stock:
            return JsonResponse({'res':4,'errmsg':'商品不足'})
        #设置hash中sku_id对应的值
        #hset  如果sku_id已经存在，更新数据，如果sku_id不存在，添加数据
        conn.hset(cart_key,sku_id,count)

        #计算用户购物车商品的条目数
        total_count = conn.hlen(cart_key)
        #返回
        return JsonResponse({'res':5,'total_count':total_count,'message':'添加成功'})

#在CartInfoView显示购物车信息中，没有结束ajax post请求，则可以使用LoginRequiredMixin类判断用户是否登录
class CartInfoView(LoginRequiredMixin,View):
    """购物车页面显示"""
    def get(self,request):
        #获取登录的用户
        user = request.user
        #获取用户购物车中商品的信息
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id
        cart_dict = conn.hgetall(cart_key)

        skus = []
        #保存用户购物车中商品的总数目和总价格
        total_count = 0
        total_price = 0
        #遍历获取商品的信息
        for sku_id,count in cart_dict.items():
            #根据商品的id，获取商品的信息
            sku = GoodsSKU.objects.get(id=sku_id)
            #计算商品的小计
            amount= sku.price*int(count)
            #动态给sku对象增加一个熟悉amount,保存商品的小计
            sku.amount = amount
            #动态给sku对象增加一个熟悉count,保存商品的数量
            sku.count = int(count)
            #添加
            skus.append(sku)

            #累加计算商品的总数目和总价格
            total_count += int(count)
            total_price += amount

        #组织上下文
        context = {
            'total_count':total_count,
            'total_price':total_price,
            'skus':skus
        }
        return render(request,'cart.html',context)

class CartUpdateView(View):
    """购物车记录添加"""
    def post(self,request):
        """购物车记录添加"""
        user = request.user
        if not user.is_authenticated:
            #用户未登录
            return JsonResponse({'res':0,'errmsg':'用户未登录'})
        #接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        #数据校验
        if not all([sku_id,count]):
            return JsonResponse({'res':1,'errmsg':'数据不完整'})
        # 校验添加的商品数量
        try:
            count = int(count)
        except Exception as e:
            #数目出错
            return JsonResponse({'res':2,'errmsg':'商品数目出错'})
        #校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            #商品不存在
            return  JsonResponse({'res':3,'errmsg':'商品不存在'})

        # 业务处理：添加购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id
        #先尝试获取sku_id的值 ->  hget cart_key 属性
        #如果sku_id在hash不存在，hget返回None

        #校验商品的库存
        if count > sku.stock:
            return JsonResponse({'res':4,'errmsg':'商品不足'})
        #设置hash中sku_id对应的值
        #hset  如果sku_id已经存在，更新数据，如果sku_id不存在，添加数据
        conn.hset(cart_key,sku_id,count)

        #计算用户购物车商品的总件数
        total_count= 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)
        #返回
        return JsonResponse({'res':5,'total_count':total_count,'message':'添加成功'})


class CartDelView(View):
    """购物车记录删除"""
    def post(self,request):
        """购物车记录添加"""
        user = request.user
        if not user.is_authenticated:
            #用户未登录
            return JsonResponse({'res':0,'errmsg':'用户未登录'})
        #接收数据
        sku_id = request.POST.get('sku_id')
        print("*"*20)
        print(sku_id+"0000000000000")
        #数据校验
        if not sku_id:
            return JsonResponse({'res':1,'errmsg':'数据不完整'})

        #校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            #商品不存在
            return  JsonResponse({'res':2,'errmsg':'商品不存在'})

        # 业务处理：添加购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id
        #删除 hdel
        conn.hdel(cart_key,sku_id)

        # 计算用户购物车商品的总件数
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        #返回
        return JsonResponse({'res':3,'total_count':total_count,'message':'添加成功'})

伊利商城/templates/base_detail_list.html
{# 详情页 列表页 #}
{% extends 'user/base.html' %}
{# 网站主体内容块 #}
{% block body %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for type in types %}
					<li><a href="{% url 'goods:index' %}" class="{{ type.logo }}">{{ type.type_name }}</a></li>
					{% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
    {# 详情页，列表页主体内容块 #}
    {% block main_content %}{% endblock main_content %}
{% endblock body %}

伊利商城/templates/base_no_cart.html
{# 购物车 提交订单 #}
{% extends 'user/base.html' %}
{% load staticfiles %}
{# 网页顶部搜索框块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{% block page_title %}{% endblock page_title %}</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
{% endblock search_bar %}

伊利商城/templates/cart.html
{% extends 'base_no_cart.html' %}
{% load staticfiles %}
{% block title %}伊利商城-购物车{% endblock title %}
{% block page_title %}购物车{% endblock page_title %}
{% block body %}
	<div class="total_count">全部商品<em>{{ total_count }}</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
    <form method="post" action="{% url 'order:place' %}">
    {% for sku in skus %}
	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="sku_ids" value="{{ sku.id }}" checked></li>
		<li class="col02"><img src="{{ sku.image.url }}"></li>
		<li class="col03">{{ sku.name }}<br><em>{{ sku.price }}元/{{ sku.unite }}</em></li>
		<li class="col04">{{ sku.unite }}</li>
		<li class="col05">{{ sku.price }}元</li>
		<li class="col06">
			<div class="num_add">
                <a href="javascript:;" class="minus fl">-</a>
				<input type="text" sku_id="{{ sku.id }}" class="num_show fl" value="{{ sku.count }}">
                <a href="javascript:;" class="add fl">+</a>
			</div>
		</li>
		<li class="col07">{{ sku.amount }}元</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>
    {% endfor %}

	<ul class="settlements">
        {% csrf_token %}
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>{{ total_price }}</em><br>共计<b>{{ total_count }}</b>件商品</li>
		<li class="col04"><input type="submit" value="去结算"></li>
	</ul>
    </form>
{% endblock body %}
{% block bottomfiles %}
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>

    // 计算被选中的商品的总件数和总价格
    function update_page_info() {
        // $('.cart_list_td').find(':checked')  获取所有被选中的商品的checkbox
        // $('.cart_list_td').find(':checked').parents('ul')   获取所有被选中的商品所在的ul元素
        total_count = 0
        total_price = 0
        $('.cart_list_td').find(':checked').parents('ul').each(function () {
            // 获取商品的数目和小计
            count = $(this).find('.num_show').val()
            amount = $(this).children('.col07').text()
            // 累加计算商品的总件数和总价格
            count = parseInt(count)
            amount = parseFloat(amount)
            total_count += count
            total_price += amount
        })
        // 设置被选中的商品的总件数和总价格
        $('.settlements').find('em').text(total_price.toFixed(2))
        $('.settlements').find('b').text(total_count)
    }

    // 商品的全选和全不选
    //:checkbox 所有type='checkbox'的<input>元素
    $('.settlements').find(':checkbox').change(function () {
        // 获取全选的checkbox的选中状态       checked: 所有被选中的元素
        is_checked = $(this).prop('checked')
        // 遍历商品的对应的checkbox，设置这些checkbox的选中状态和全选的checkbox保持一致
        //each 遍历
        $('.cart_list_td').find(':checkbox').each(function () {
            $(this).prop('checked', is_checked)
        })
        // 更新页面的信息
        update_page_info()
    })

    // 商品对应的checkbox状态发生改变时，设置全选checkbox的状态
    $('.cart_list_td').find(':checkbox').change(function () {
        // 获取页面上所有商品的数目
        all_len = $('.cart_list_td').length
        // 获取页面上被选中的商品的数目
        checked_len = $('.cart_list_td').find(':checked').length
        is_checked = true
        if (checked_len < all_len){
            is_checked = false
        }
        $('.settlements').find(':checkbox').prop('checked', is_checked)
        // 更新页面的信息
        update_page_info()
    })

    // 计算商品的小计
    function update_goods_amount(sku_ul) {
        // 获取商品的价格和数量
        count = sku_ul.find('.num_show').val()
        price = sku_ul.children('.col05').text()
        // 计算商品的小计
        amount = parseInt(count)*parseFloat(price)
        // 设置商品的小计
        sku_ul.children('.col07').text(amount.toFixed(2)+'元')
    }

    // 更新购物车中商品的数量
    error_update = false
    total = 0
    function update_remote_cart_info(sku_id, count) {
        csrf = $('input[name="csrfmiddlewaretoken"]').val()
        // 组织参数
        params = {'sku_id':sku_id, 'count':count, 'csrfmiddlewaretoken':csrf}
        // 设置ajax请求为同步
        //因为上面total设置为0  当你重新增加数量时ajax的处理是异步的，不会调用回调函数，有可能为购物件数为0
        //所以这里设置ajax为同步，处理回调函数后再设为异步，这样的购物件数就可以显示正常了
        $.ajaxSettings.async = false
        // 发起ajax post请求，访问/cart/update, 传递参数:sku_id count
        // 默认发起的ajax请求都是异步的，不会等回调函数执行
        $.post('/cart/update/', params, function (data) {
            if (data.res == 5){
                // 更新成功
                error_update = false
                total = data.total_count
            }
            else{
                // 更新失败
                error_update = true
                alert(data.errmsg)
            }
        })
        // 设置ajax请求为异步
        $.ajaxSettings.async = true
    }

    // 购物车商品数量的增加
    $('.add').click(function () {
        // 获取商品的id和商品的数量
        sku_id = $(this).prev().attr('sku_id')
        count = $(this).prev().val()
        // 组织参数
        count = parseInt(count)+1

        // 更新购物车记录
        update_remote_cart_info(sku_id, count)

        // 判断更新是否成功
        if (error_update == false){
            // 重新设置商品的数目
            $(this).prev().val(count)
            // 计算商品的小计
            update_goods_amount($(this).parents('ul'))
            // 获取商品对应的checkbox的选中状态，如果被选中，更新页面信息
            is_checked = $(this).parents('ul').find(':checkbox').prop('checked')
            if (is_checked){
                // 更新页面信息
                update_page_info()
            }
            // 更新页面上购物车商品的总件数
            $('.total_count').children('em').text(total)
        }
    })

    // 购物车商品数量的减少
    $('.minus').click(function () {
        // 获取商品的id和商品的数量
        sku_id = $(this).next().attr('sku_id')
        count = $(this).next().val()

        // 校验参数
        count = parseInt(count)-1
        if (count <= 0){
            return
        }

        // 更新购物车中的记录
        update_remote_cart_info(sku_id, count)

        // 判断更新是否成功
        if (error_update == false){
            // 重新设置商品的数目
            $(this).next().val(count)
            // 计算商品的小计
            update_goods_amount($(this).parents('ul'))
            // 获取商品对应的checkbox的选中状态，如果被选中，更新页面信息
            is_checked = $(this).parents('ul').find(':checkbox').prop('checked')
            if (is_checked){
                // 更新页面信息
                update_page_info()
            }
            // 更新页面上购物车商品的总件数
            $('.total_count').children('em').text(total)
        }
    })

    // 记录用户输入之前商品的数量
    pre_count = 0
    $('.num_show').focus(function () {
        pre_count = $(this).val()
    })

    // 手动输入购物车中的商品数量
    $('.num_show').blur(function () {
        // 获取商品的id和商品的数量
        sku_id = $(this).attr('sku_id')
        count = $(this).val()

        // 校验参数
        if (isNaN(count) || count.trim().length==0 || parseInt(count)<=0){
            // 设置商品的数目为用户输入之前的数目
            $(this).val(pre_count)
            return
        }

        // 更新购物车中的记录
        count = parseInt(count)
        update_remote_cart_info(sku_id, count)

        // 判断更新是否成功
        if (error_update == false){
            // 重新设置商品的数目
            $(this).val(count)
            // 计算商品的小计
            update_goods_amount($(this).parents('ul'))
            // 获取商品对应的checkbox的选中状态，如果被选中，更新页面信息
            is_checked = $(this).parents('ul').find(':checkbox').prop('checked')
            if (is_checked){
                // 更新页面信息
                update_page_info()
            }
            // 更新页面上购物车商品的总件数
            $('.total_count').children('em').text(total)
        }
        else{
            // 设置商品的数目为用户输入之前的数目
            $(this).val(pre_count)
        }
    })

    // 删除购物车中的记录
    $('.cart_list_td').children('.col08').children('a').click(function () {
        // 获取对应商品的id
        sku_id = $(this).parents('ul').find('.num_show').attr('sku_id')
        csrf = $('input[name="csrfmiddlewaretoken"]').val()
        // 组织参数
        params = {'sku_id':sku_id, 'csrfmiddlewaretoken':csrf}
        // 获取商品所在的ul元素
        sku_ul = $(this).parents('ul')
        // 发起ajax post请求， 访问/cart/delete, 传递参数:sku_id
        $.post('/cart/del/', params, function (data) {
            if (data.res == 3){
                // 删除成功，异常页面上商品所在的ul元素
                sku_ul.remove()
                // 获取sku_ul中商品的选中状态
                is_checked = sku_ul.find(':checkbox').prop('checked')
                if (is_checked){
                    // 更新页面信息
                    update_page_info()
                }
                // 重新设置页面上购物车中商品的总件数
                $('.total_count').children('em').text(data.total_count)
            }
            else{
                alert(data.errmsg)
            }
        })
    })

    </script>
{% endblock bottomfiles %}

伊利商城/templates/index.html
{% extends 'user/base.html' %}
{% load staticfiles %}
{% block title %}伊利商城-首页{% endblock title %}
{% block topfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}
{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
{#        遍历分类信息#}
            {% for type in types %}
			<li><a href="#model0{{ forloop.counter }} "  class="{{ type.logo }}">{{ type.type_name }}</a></li>
            {% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
{#            遍历轮播图#}
                {% for banner in goods_banners %}
                    <li><a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.image.url }}" alt="幻灯片"></a></li>
                {% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
{#            {% for banner in promotion_banners %}#}
{#			<a href="{{ banner.url }}"><img src="{{ banner.image.url }}"></a>#}
{#            {% endfor %}#}
		</div>
	</div>
{#    遍历每个类别的详细信息#}
    {% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type.type_name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
{#            商品的文字信息#}
                {% for banner in type.title_banners %}
				<a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a>
                    {% endfor %}
			</div>
			<a href="{% url 'goods:list' type.id 1 %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
			<ul class="goods_list fl">
{#            商品图片信息#}
                {% for banner in type.image_banners %}
				<li>
					<h4><a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.sku.image.url }}"></a>
					<div class="prize">{{ banner.sku.price }}</div>
				</li>
                    {% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}
{% endblock body %}

伊利商城/templates/list.html
{% extends 'base_detail_list.html' %}

{% block title %}伊利商城-商品列表{% endblock title %}
{% block main_content %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ type.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
						<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' type.id 1 %}" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=price" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=hot" {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for sku in sku_page.object_list %}
				<li>
					<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
					<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku.price }}</span>
						<span class="unit">{{ sku.price}}/{{ sku.unite }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>

			<div class="pagenation">
{#                如果有上一页#}
                {% if sku_page.has_previous %}
                    <a href="{% url 'goods:list' type.id sku_page.previous_page_number %}?sort={{ sort }}">上一页</a>
                {% endif %}
{#                页码的显示#}
                {% for pindex in pages %}
{#                    如果等于当前页#}
                    {% if pindex == sku_page.number %}
				        <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}" class="active">{{ pindex }}</a>
                    {% else %}
				        <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}">{{ pindex }}</a>
                    {% endif %}1
				{% endfor %}
{#                如果有下一页#}
                {% if sku_page.has_next %}
				<a href="{% url 'goods:list' type.id sku_page.next_page_number %}?sort={{ sort }}">下一页</a>
                {% endif %}
			</div>
{#            <div class="pagenation">#}
{#              {% if sku_page.has_previous %}#}
{# <li class="long"><a href="?{{ sku_page.previous_page_number.querystring }}" >上一页</a></li>#}
{#             {% endif %}#}
{#          {% for page in sku_page.pages %}#}
{#        {% if page %}#}
{#            {% ifequal page sku_page.number %}#}
{#                   <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>#}
{#            {% else %}#}
{#<li><a href="?{{ page.querystring }}">{{ page }}</a></li>#}
{#            {% endifequal %}#}
{#        {% else %}#}
{#            <li class="none"><a href="">...</a></li>#}
{#        {% endif %}#}
{#    {% endfor %}#}
{#    {% if sku_page.has_next %}#}
{#    <li class="long"><a href="?{{ sku_page.next_page_number.querystring }}">下一页</a></li>#}
{#    {% endif %}#}
{#         </div>#}
		</div>
	</div>
{% endblock main_content %}