伊利商城/apps/cart/urls.py
from django.contrib import admin
# from django.urls import path
from django.conf.urls import url,include
from .views import CartAddView,CartInfoView,CartUpdateView,CartDelView

urlpatterns = [
    url('add/',CartAddView.as_view(),name='add'),
    url('update/',CartUpdateView.as_view(),name='update'),
    url('del/',CartDelView.as_view(),name='del'),
    url('^',CartInfoView.as_view(),name='list'),
]

伊利商城/apps/goods/urls.py
from django.contrib import admin
# from django.urls import path
from django.conf.urls import url,include

from .views import IndexView,goods_listView,DetailView

urlpatterns = [
    url('index/$', IndexView.as_view(), name='index'),
    url('list/(?P<type_id>\d+)/(?P<pages>\d+)/$', goods_listView.as_view(), name='list'),
    url(r'detail/(?P<good_id>\d+)/$', DetailView.as_view(), name='detail'),

]

伊利商城/apps/user/urls.py
from django.contrib import admin
# from django.urls import path
from django.conf.urls import url,include
from .views import RegisterView,LoginView,ActiveView,UserInfoView,UserOrderView,UserSiteView

urlpatterns = [
    url('active/(?P<token>.*)/$',ActiveView.as_view(),name='active'),
    url('info/$', UserInfoView.as_view(), name='info'),
    url('order/(?P<page>\d+)$', UserOrderView.as_view(), name='order'),
    url('site/$', UserSiteView.as_view(), name='site'),
]

伊利商城/yili/urls.py
from django.contrib import admin
# from django.urls import path
from django.conf.urls import url,include
from user.views import RegisterView,LoginView,LogoutView
urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'tinymce/',include('tinymce.urls')),
    url(r'^search/', include('haystack.urls')), #全文检索框架
    # 注册
    url('^register/$', RegisterView.as_view(), name='register'),
    url('^login/$', LoginView.as_view(), name='login'),
    url('^logout/$', LogoutView.as_view(), name='logout'),

    url(r'^user/',include(('user.urls','user'),namespace='user')),
    url(r'^cart/',include(('cart.urls','cart'),namespace='cart')),
    url(r'^order/',include(('order.urls','order'),namespace='order')),
    url(r'^',include(('goods.urls','goods'),namespace='goods')),
]

伊利商城/apps/user/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser
from django.db import models

from db.base_model import BaseModel

# Create your models here.

class UserProfile(AbstractUser,BaseModel):

    class Meta:
        db_table = 'df_user'
        verbose_name = '用户'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.username

    # def get_address(self):
    #     return self.address_set.get(user=self.username)

class AddressManager(models.Manager):
    """地址模型管理器类"""
    #应用场景
   #1.改变原有查询的结果集：all()
   #2.封装方法：用户操作模型类对应的数据表（增删改查）
    def get_default_address(self,user):

       """获取用户默认收货地址"""
       #self.model:获取self对象所在的模型类
       #self可直接调用我们models.Manager get方法
       try:
           address = self.get(user=user,is_default=True)  # 使用到了默认的模型管理器：models.Manage(address.objects)
       except self.model.DoesNotExist:

           address = None
       return address


class Address(BaseModel):
    """
    地址模型类
    """
    user = models.ForeignKey(UserProfile,on_delete=models.CASCADE,verbose_name='所属用户')
    receiver = models.CharField(max_length=20,verbose_name='收件人')
    address = models.CharField(max_length=256,verbose_name='收件地址')
    zip_code = models.CharField(max_length=6,null=True,verbose_name='邮政编码')
    phone = models.CharField(max_length=11,verbose_name='联系电话')
    is_default = models.BooleanField(default=False,verbose_name='是否默认地址')

    #自定义一个模型管理器对象
    objects = AddressManager()

    class Meta:
        db_table = 'df_address'
        verbose_name = '地址'
        verbose_name_plural = verbose_name


伊利商城/apps/user/forms.py
# _*_ coding:utf-8 _*_
__author__ = 'cc'
__date__ = '2019/6/3 15:26'
import re
from .models import UserProfile,Address
from django import forms

def email_check(email):
    pattern = re.compile(r"\"?([-a-zA-Z0-9.~?{}]+@\w+\.\w+)\"?")
    return re.match(pattern,email)

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=20)
    password1 = forms.CharField(min_length=6)
    password2 = forms.CharField(min_length=6)
    email = forms.EmailField()
    is_xy = forms.BooleanField(required=False)

    def clean_username(self):
        username = self.cleaned_data.get('username')

        filter_result = UserProfile.objects.filter(username=username)
        if len(filter_result) > 0:
            raise forms.ValidationError("username is exist!")

        return username

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')

        if len(password1) < 6:
            raise forms.ValidationError("password is too short")
        return password1

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1!=password2:
            raise forms.ValidationError("password inconformity!")

        return password2

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if email_check(email):
            filter_result = UserProfile.objects.filter(email=email)
            if len(filter_result) > 0:
                raise forms.ValidationError('email 已注册过了')
        else:
            raise forms.ValidationError('email error!')

        return email

class LoginForm(forms.Form):
    username = forms.CharField(label='username',max_length=20)
    pwd = forms.CharField(label='pwd',min_length=6)

class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['receiver','address','zip_code','phone']

    def clean_zip_code(self):
        zip_code = self.cleaned_data['zip_code']

        if len(zip_code) > 6 or len(zip_code) < 6:
            raise forms.ValidationError("邮箱格式不正确！")

        return zip_code

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        REGEX_MOBILE = "^1[358]\d{9}$|^147\d{8}$|^176\d{8}$"  # 正则手机号
        p = re.compile(REGEX_MOBILE)
        if p.match(phone):
            return phone
        else:
            raise forms.ValidationError("手机号非法！")




伊利商城/apps/user/views.py
from django.shortcuts import render,get_object_or_404
from django.views.generic import View
from django.conf import settings
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from django.http import HttpResponseRedirect,HttpResponse
from django_redis import get_redis_connection
from django.core.paginator import Paginator

from .forms import RegisterForm,LoginForm,AddressForm
from .models import Address,UserProfile as User
from goods.models import GoodsSKU
from utils.mixin import LoginRequiredMixin
from order.models import OrderInfo,OrderGoods

from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from itsdangerous import SignatureExpired
from celery_tasks.tasks import send_register_active_email,send_mail

import re

class RegisterView(View):
    def get(self,request):
        return render(request,'register.html',{})
    def post(self,request):
        forms = RegisterForm(request.POST)
        if forms.is_valid():
            username = forms.cleaned_data['username']
            password = forms.cleaned_data['password2']
            email = forms.cleaned_data['email']

            user = User.objects.create_user(username=username,password=password,email=email)
            user.is_active=0
            user.save()

            #发送激活邮件，包含激活链接：http://127.0.0.1:8000/user/active/1
            #激活链接中需要包含用户的身份信息   并且要把身份信息进行加密
            #加密用户的身份信息，生成激活token
            serializer = Serializer(settings.SECRET_KEY,3600)   #实例化对象
            info = {'confirm':user.id}
            token = serializer.dumps(info)          #加密  bytes类型
            token = token.decode()    #解码   字符串
            #发邮件
            # subject = 'ttsx欢迎信息'
            # message = '{0},欢迎您，请点击下面链接激活您的账户:http://127.0.0.1:8000/user/active/{1}'.format(username, token)
            # sender = settings.EMAIL_FROM
            # receiver = [email]
            # send_mail(subject, message, sender, receiver)
            send_register_active_email.delay(email,username,token)

        return render(request, 'register.html', {'msg':forms})

class ActiveView(View):
    def get(self,request,token):
        serializer = Serializer(settings.SECRET_KEY, 3600)      #实例化对象

        try:
            info = serializer.loads(token)
            #获取待激活用户的id
            user_id = info['confirm']
            #根据id获取用户信息
            user = User.objects.get(id=user_id)
            user.is_active = 1
            user.save()

            #跳转到登录页面
            return HttpResponseRedirect(reverse('login'))

        except SignatureExpired as e:
            #激活链接已过期
            return HttpResponse("激活链接已过期")

class LoginView(View):
    def get(self,request):
        #判断是否记住了用户名
        print(request)
        print("*********************")
        if 'username' in request.COOKIES:
            username = request.COOKIES.get('username')
            checked = 'checked'
        else:
            username = ''
            checked = ''

        return render(request,'login.html',{'username':username,'checked':checked})

    def post(self,request):
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            pwd = login_form.cleaned_data['pwd']
            #cache.set('name2','cc',timeout=None)
            user = authenticate(username=username,password=pwd)
            if user is not None:
                login(request,user)
                #获取登录后所要跳转的地址，如果没有则goods：index
                next_url = request.GET.get('next', reverse('goods:index'))
                response = HttpResponseRedirect(next_url)
                #判断是否需要记住用户名
                remember = request.POST.get('remember')
                if remember == 'on':
                    #记住用户名
                    response.set_cookie('username',username,max_age=7*24*3600)
                else:
                    response.delete_cookie('username')
                return response
            else:
                return render(request, 'login.html', {'errmsg':'账号未激活'})

                # return HttpResponseRedirect(next_url)
        else:
            return render(request,'login.html',{})


class LogoutView(View):
    def get(self,request):
        #清除用户的session信息
        logout(request)
        #跳转到登录页面
        return HttpResponseRedirect(reverse('login'))


class UserInfoView(LoginRequiredMixin,View):
    def get(self,request):
        page = 'info'

        #获取用户信息
        user = request.user
        #获取用户默认收货地址
        address = Address.objects.get_default_address(user=user)

       #获取用户的历史浏览记录
        #原生redis连接
        # from redis import StrictRedis
        # sr = StrictRedis(host='192.168.2.127',port='6379',db=2)
        #调用redis作为django缓存的连接
        con = get_redis_connection('default')
        history_key = 'history_%d'%user.id

        #获取用户最新浏览的5个商品的id
        sku_ids = con.lrange(history_key,0,4)

        #从数据库中查询用户浏览的商品具体信息
        goods_li = GoodsSKU.objects.filter(id__in=sku_ids)

        #遍历获取用户浏览的商品信息
        goods_li =[]
        for id in sku_ids:
            goods = GoodsSKU.objects.get(id=id)
            goods_li.append(goods)

        #组织上下文
        context = {
            'page':'user',
            'address':address,
            'goods_li':goods_li
        }
        # request.user.is_authenticated()
        # 除了你给模板文件传递的模板变量之外，
        # django框架会把request.user也传给模板文件（也就是说你可以直接在模板文件使用user.is_authenticated()进行判断）
        return render(request,'user/user_center_info.html',context)


    # def get(self,request):
    #     page = 'info'
    #     #获取用户信息
    #     user = request.user
    #     #获取用户默认收货地址
    #     address = Address.objects.get_default_address(user=user)
    #
    #     # 获取用户的历史浏览记录
    #     # from redis import StrictRedis
    #     # sr = StrictRedis(host='172.16.179.130', port='6379', db=9)
    #     # con = get_redis_connection('default')
    #
    #     history_key = 'history_%d' % user.id
    #
    #     # 获取用户最新浏览的5个商品的id
    #     # sku_ids = con.lrange(history_key, 0, 4)  # [2,3,1]
    #
    #     # 遍历获取用户浏览的商品信息
    #     goods_li = []
    #     # for id in sku_ids:
    #     #     goods = GoodsSKU.objects.get(id=id)
    #     #     goods_li.append(goods)
    #     return render(request,'user/user_center_info.html',{'page':page,'address':address,'goods_li':goods_li})

#用户中心订单页
class UserOrderView(LoginRequiredMixin,View):
    def get(self,request,page):
        page = 'order'
        #获取用户的订单信息
        user = request.user
        orders = OrderInfo.objects.filter(user=user).order_by('order_id')
        for order in orders:
            order_skus = OrderGoods.objects.filter(order=order.order_id)
            #遍历order_skus计算商品的小计
            for order_sku in order_skus:
                #计算小计
                amount = order_sku.count*order_sku.price
                #动态给order_sku增加属性amount，保存订单商品的小计
                order_sku.amount = amount

            #动态给order增加属性，保存订单状态标题
            order.status.name = OrderInfo.ORDER_STATUS[order.order_status]
            #动态给order增加属性，保存订单商品的信息
            order.order_skus = order_skus

        #分页
        paginator = Paginator(orders,1)
        print(paginator.num_pages)
        # 获取第page页的内容
        try:
            page = int(page)
        except Exception as e:
            page = 1
        if page > paginator.num_pages:
            page = 1
        # 获取第page页的Page实例对象
        order_page = paginator.page(page)

        # todo:进行页码的控制，页面上最多显示5个页码
        # 1. 总页数小于5页，页面上显示所有页码
        # 2. 如果当前页是前3页，显示1-5页
        # 3. 如果当前页是后3页，显示后5页
        # 4. 其他情况，显示当前页的前2页，当前页，当前页后两页。
        num_pages = paginator.num_pages
        print(num_pages)
        if num_pages < 5:
            pages = range(1, num_pages + 1)
        elif page <= 3:
            pages = range(1, 6)
        elif num_pages - page <= 2:
            pages = range(num_pages - 4, num_pages + 1)
        else:
            pages = range(page - 2, page + 3)

        #组织上下文
        context = {'order_page':order_page,
                   'pages':pages,
                   'page':'order'}

        return render(request,'user/user_center_order.html',context)


#地址
class UserSiteView(LoginRequiredMixin,View):
    def get(self,request):
        page = 'site'
        user = request.user
        # 获取用户默认地址
        address = Address.objects.get_default_address(user=user)

        return render(request,'user/user_center_site.html',{'page':page,'address':address})

    def post(self,request):
        """地址的添加"""
        #接收数据
        receiver = request.POST.get('receiver')
        addr = request.POST.get('addr')
        zip_code = request.POST.get('zip_code')
        phone =request.POST.get('phone')
        print(receiver,addr,zip_code,phone)
        #校验数据
        if not all([receiver,addr,phone]):
            # print("11")
            return render(request,'user/user_center_site.html',{'errmsg':"数据不完整"})
        if not re.match(r'^1[3|4|5|7|8][0-9]{9}$',phone):
            # print("22")
            return render(request,'user/user_center_site.html',{'errmsg':"手机格式错误！"})

        #地址添加
        user = request.user

        # 获取用户默认地址
        address = Address.objects.get_default_address(user=user)

        if address:
            is_default = False
        else:
            is_default = True
        # print(address.is_default)
        Address.objects.create(user=user,receiver=receiver,address=addr,phone=phone,is_default=is_default)
        # Address.save()
        # return render(request,'user/user_center_site.html',{'form_add':form_add})
        return HttpResponseRedirect(reverse('user:site'))

伊利商城/templates/user/base.html
{# 首页 注册 登录 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页标题内容块 #}
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	{# 网页顶部引入文件块 #}
    {% block topfiles %}{% endblock topfiles %}
</head>
<body>
{# 网页顶部欢迎信息块 #}
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到伊利商城!</div>
			<div class="fr">
                {% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
					<a href="{% url 'logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:info' %}">用户中心</a>
					<span>|</span>
					<a href={% url 'cart:list' %} }>我的购物车</a>
{#                    <a href="#">我的购物车</a>#}
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
{% endblock header_con %}

{# 网页顶部搜索框块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="images/logo.png"></a>
		<div class="search_con fl">
            <form method="get" action="/search">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:list' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>
{% endblock search_bar %}

{# 网站主体内容块 #}
{% block body %}{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
	</div>
    {# 网页底部html元素块 #}
    {% block bottom %}{% endblock bottom %}
    {# 网页底部引入文件块 #}
	{% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>

伊利商城/templates/user/base_detail_list.html
{# 详情页 列表页 #}
{% extends 'user/base.html' %}
{# 网站主体内容块 #}
{% block body %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for type in types %}
					<li><a href="#" class="{{ type.logo }}">type.</a></li>
                    {% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
    {# 详情页，列表页主体内容块 #}
    {% block main_content %}{% endblock main_content %}
{% endblock body %}

伊利商城/templates/user/base_no_cart.html
{# 购物车 提交订单 #}
{% extends 'user/base.html' %}
{% load staticfiles %}
{# 网页顶部搜索框块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{% block page_title %}{% endblock page_title %}</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
{% endblock search_bar %}

伊利商城/templates/user/base_user_center.html
{# 用户中心3页面 #}
{% extends 'user/base_no_cart.html' %}
{% block title %}伊利商城-用户中心{% endblock title %}
{% block page_title %}用户中心{% endblock page_title %}
{% block body %}
    <div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:info' %}" {% if page == 'info' %}class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:order' 1 %}" {% if page == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:site' %}" {% if page == 'site' %}class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
        {# 用户中心右侧内容块 #}
        {% block right_content %}{% endblock right_content %}
    </div>
{% endblock body %}

伊利商城/templates/user/user_center_info.html
{% extends 'user/base_user_center.html' %}
{% block right_content %}
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ user.username }}</li>
                            {% if address %}
                                <li><span>联系方式：</span>{{ address.phone }}</li>
                                <li><span>联系地址：</span>{{ address.address }}</li>
                            {% else %}
                                <li><span>联系方式：</span>无默认</li>
							    <li><span>联系地址：</span>无默认</li>
                            {% endif %}
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
                        {% for goods in goods_li %}
				        <li>
                            <a href="{% url 'goods:detail' goods.id %}"><img src="{{ goods.image.url }}"></a>
                            <h4><a href="{% url 'goods:detail' goods.id %}">{{ goods.name }}</a></h4>
                            <div class="operate">
                                <span class="prize">￥{{ goods.price }}</span>
                                <span class="unit">{{ goods.price }}/{{ goods.unite }}</span>
                                <a href="#" class="add_goods" title="加入购物车"></a>
                            </div>
                        </li>
                        {% empty %}
                            无历史浏览记录
                        {% endfor %}
			        </ul>
		        </div>
		</div>
{% endblock right_content %}


伊利商城/templates/user/user_center_order.html
{% extends 'user/base_user_center.html' %}
{% block right_content %}
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
            {% for order in order_page %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ order.create_time }}</li>
					<li class="col02">{{ order.order_id }}</li>
					<li class="col02 stress">{{ order.status_name }}</li>
				</ul>
				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for order_sku in order.order_skus %}
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="{{ order_sku.sku.image.url }}"></li>
									<li class="col02">{{ order_sku.sku.name }}<em>{{ order_sku.price }} 元/{{ order_sku.sku.unite }}</em></li>
									<li class="col03">{{ order_sku.count }}</li>
									<li class="col04">{{ order_sku.amount }}元</li>
								</ul>
                                {% endfor %}

							</td>
							<td width="15%">{{ order.total_price|add:order.transit_price }}(含运费)</td>
							<td width="15%">{{ order.status_name }}</td>
							<td width="15%"><a href="#" class="oper_btn" status="{{ order.order_status }}">去付款</a></td>
						</tr>
					</tbody>
				</table>
            {% endfor %}


				<div class="pagenation">
                    {% if order_page.has_previous_page %}
					<a href="{% url "user:order" order_page.previous_page_number %}"><上一页</a>
                    {% endif %}

					{% for pindex in pages %}
                        {% if pindex == order_page.number %}
                            <a href="{% url "user:order" pindex %}" class="active">{{ pindex }}</a>
                        {% else %}
					        <a href="{% url "user:order" pindex %}">{{ pindex }}</a>
                        {% endif %}
				    {% endfor %}

					{% if order_page.has_next_page %}
                    <a href="{% url "user:order" order_page.next_page_number %}">下一页></a>
                    {% endif %}
				</div>
		</div>
{% endblock right_content %}
{% block bottomfiles %}
<script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script>

    $(".oper_btn").each(function () {
        //获取支付状态
        status = $(this).attr('status')
        if(status ==1){
            $(this).text('去支付 ')
        }
        else if (status == 4){
            $(this).text('去评价')
        }
        else if (status == 5){
            $(this).text('已完成')
        }

    })
    $('.oper_btn'.click(function () {
        //获取status
        //获取订单id
        order_id = $(this).attr('order_id')
        status = $(this).attr('status')
        if (status == 1){
            //进行支付
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            //组织参数
            params = { 'order_id':order_id,'csrfmiddlewaretoken':csrf}
            //发起ajax post请求，访问/order/pay,传递参数：order_id
            $.post('/order/pay',params,function (data) {
                if (data.res == 3){
                    //引导用户到支付页面
                    window.open(data.pay_url)
                }
                else{
                    alert(data.errmsg)
                }
            })
        }
        else if (status == 4){
            //其他情况
            //跳转到评价页面
            location.href = '/order/comment/'+order_id
        }
    }))
</script>
{% endblock bottomfiles %}

伊利商城/templates/user/user_center_site.html
{% extends 'user/base_user_center.html' %}
{% block right_content %}
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
                        {% if address %}
						    <dd>{{ address.address }} （{{ address.receiver }} 收） {{ address.phone }}</dd>
					    {% else %}
                            <dd>无默认地址</dd>
                        {% endif %}
                    </dl>
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form method="post">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="receiver">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="addr"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="zip_code">
						    {{ form_add.errors.zip_code }}
                        </div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="phone">
                            {{ form_add.errors.phone }}
						</div>

						<input type="submit" value="提交" class="info_submit">
                        {{ errmsg }}
					</form>
				</div>
		</div>
{% endblock right_content %}